apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: bookreview
  labels:
    app: web
    env: prod
spec:
  selector:
    matchLabels:
      app: web
  replicas: 2
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web-container
          image: book-review-app/web:gitops
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
