apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bookreview

  # - ingress/ingress.yaml
  # - web/deployment.yaml
  # - web/service.yaml
resources:
- namespace.yaml
- test-ingress.yaml
- api/deployment.yaml
- api/service.yaml
- api/configmap.yaml
- database/deployment.yaml
- database/service.yaml
- database/configmap.yaml
- redis/deployment.yaml
- redis/service.yaml

images:
- name: book-review-app/api
  newName: 462035739353.dkr.ecr.ap-northeast-2.amazonaws.com/book-review-app/api
  newTag: 47e658
- name: book-review-app/web
  newName: docker.io/YOUR_DOCKERHUB_USERNAME/book-review-app/web
  newTag: v1
